### ISSUE TITLE
Properly handle missing response from MLS

### ISSUE THREAD

**Issue by mweinelt** [freifunk-darmstadt/ffda-domain-director#1]
```
Traceback (most recent call last):
  File "/var/lib/director/venv/lib/python3.4/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/director/venv/lib/python3.4/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/director/venv/lib/python3.4/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/lib/director/venv/lib/python3.4/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/lib/director/venv/lib/python3.4/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/director/venv/lib/python3.4/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/director/domain-director/domain_director/blueprints.py", line 43, in serve
    "location": {"lat": mls_response.lat,
AttributeError: 'NoneType' object has no attribute 'lat'
```

**Comment by blocktrron** [comment]
This was an oversight before https://github.com/freifunk-darmstadt/ffda-domain-director/commit/9fb1cc41cf2e6a5734f500a752970938ec049151

It does not occur when using at least this commit.
